language: ruby
rvm:
- 2.1

script:
- bundle exec jekyll build --config _config.yml,_config_deploy.yml
- bundle exec htmlproof ./_site --only-4xx --disable-external

deploy:
  provider: s3
  access_key_id: 
    secure: Sg6PQ39qBA9xDbb3m7cwWmHuwg7V9U0m7Rp8/tFncqxGZMAkmBh8GeKlJOyoiAn85ejEnpHk58SQytmaP7JZRhyXLEwPaKWRaUmWwTDtE1GNxEiWxx/uPti/TjkMa+7cC5eMlNU66O4EYOLQnSCgwyy7Urrk6Px/3IDzvMmkXyP4Bsl7/7ZW/5an3kiD/6yrbuoZG7MUFPrUpSkBn8kebpfiI3Qow7rwl2YZJO/MwGPln25ueo8XiS/BNgNMVsD6IdnfhLG2I4oBvDAz/+Ks93FUI6D8PB94HEbLCPoHT9YwwFGA1xAS5q5KXR3KtrXvGaWoSvr2qAS8IVTiqqK1BIDUlGInbImw1/a0zqGA31N1ZnzSPtAx3W0Bwv7zhi8++hcAwx29e6y+ZsvSk79J8pB+jYI4ekzMQLDTazdUgQiIL6p99GXkJcw1xVyXQ3bRG+H1tcDBVeVlaiKCvakgFgW5+3630WyX8bw7UnTkcb9qe6M5Eq9zJlfE7oVYz1oNmU8fi+SAUYq6BZ3Hj1tsYAfx8+YYejrxs4VOC1ZDT6pjHVWBf9zAvyGXaO8z5ShJEtWi7QNbEQp/a7XA3FWga82LmZzZSrKP/7l371DI7Qlj8wzdXnt8YNWb2XfbkkZ6GAjFESGbKzu35sM7Je81v03NyOnv/Xhg4KbwOqqomys=
  secret_access_key:
    secure: V6DyQ78o1r6RVl82QLBOtPzQ1kNOxbm+bGlq0VuRlx7Nh8mMi8SQVTtr6RVP80aoK5j0M8dC9PJ+8mKdDwHeQZVJFbOC1EiEr4I33RnO/gMLDQLD4fHj7SXBlkRGfDRgVnOVyz4yPAerou+S44IBBnTwR4GNarHun6vNMj36Ku3kJtEMoQ5chUxLJZ4yYe91Q9bna9RpjN8ZZa9n1Rz9DNsKHvE7xusg4oNENZoHtJbbFn+q5L5a6+M3RhSTcB0+Gbo/Ykt0CmCEqJwKagVnj/Hbf3NaV+SS+bb/aTfNcHtGxGck/tyDpspobDJf+UfPV4trYC3ivMz4tWWFjSZ5tomQAE4/7RmDPG83NWHQzyFC4Omc5YNU36XSmEtGlx1Ng1Ux5ZIEYTF0M7+SMmXNeXTlnzCDisr6FgLdI8cClDMvX7pRXbqPrjYP0cR6HxTPo8l6b5QoJRMu0Vp0anDLONNjCC6TaH82a2yuNfPE+9uAUeebLBsCLn0FDZKjI301QuSOoIEnya4NfPjedn2pjTFabxK1k3i2P6YztFQm34fNJjr52SHwzJ0FCs6DtG6TTptd1uSwyd715i1UMY663sbW0oyircC1cHlK/4PKxzgvaI0jyCDEaFFminf76084QikhmipDHihlNxVDPGfcy//7yQkhLUa9Pfe/Gh/LUhg=
  bucket: "simonlee.me"
  skip_cleanup: true
  region: eu-west-1
  local_dir: _site

branches:
  only:
  - master
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
